'use client';

import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowUpRight, ChevronDown, CircleHelp, ExternalLink, LayoutGrid, List, Menu, Search, ShieldCheck, SlidersHorizontal, Wallet, X, Zap } from 'lucide-react';

type Category = 'All agents' | 'Rebalancing' | 'Grid Trading' | 'Yield Optimisation' | 'Health Factor';
type Agent = { id:string; name:string; category:Exclude<Category,'All agents'>; protocol:string; online:boolean; price:string; unit:string; description:string; metrics:[string,string,string]; accent:string; icon:string; score:string; activated?:boolean };

const agents: Agent[] = [
  {id:'grid-bnb-usdt',name:'Grid BNB / USDT',category:'Grid Trading',protocol:'PancakeSwap',online:true,price:'$4.00',unit:'per task',description:'Runs a disciplined grid within your price range, re-posting orders after every fill.',metrics:['68.4% win rate','30 day window','−8.2% max drawdown'],accent:'#e2b75c',icon:'↕',score:'4.9'},
  {id:'grid-alpha-v2',name:'Grid Alpha v2',category:'Grid Trading',protocol:'Thena',online:true,price:'$7.00',unit:'per task',description:'Adaptive grid that widens spacing as volatility expands.',metrics:['72.1% win rate','30 day window','−11.4% max drawdown'],accent:'#e2b75c',icon:'◫',score:'4.7'},
  {id:'lp-range-keeper',name:'LP Range Keeper',category:'Rebalancing',protocol:'PancakeSwap v3',online:true,price:'$12',unit:'monthly',description:'Keeps your concentrated liquidity in range and resets when price exits.',metrics:['91.6% in-range','14 resets',' $184K TVL'],accent:'#8ac6a7',icon:'⌁',score:'4.8'},
  {id:'range-pilot',name:'Range Pilot',category:'Rebalancing',protocol:'PancakeSwap v3',online:false,price:'$8',unit:'monthly',description:'A conservative range manager tuned for lower gas and fewer resets.',metrics:['87.3% in-range','9 resets',' $96K TVL'],accent:'#8ac6a7',icon:'◌',score:'4.6'},
  {id:'stable-router',name:'Stable Router',category:'Yield Optimisation',protocol:'Venus · Lista',online:true,price:'$9',unit:'monthly',description:'Routes stablecoin liquidity to the highest realised APR across trusted venues.',metrics:['14.8% actual APR','6 migrations',' $1.2M managed'],accent:'#9eb8e8',icon:'↗',score:'4.9'},
  {id:'yield-scout',name:'Yield Scout',category:'Yield Optimisation',protocol:'Lista',online:true,price:'$5.00',unit:'per task',description:'Scans lending markets for spread and moves only when the edge clears gas.',metrics:['12.6% actual APR','3 migrations',' $420K managed'],accent:'#9eb8e8',icon:'⌘',score:'4.5'},
  {id:'venus-guardian',name:'Venus Guardian',category:'Health Factor',protocol:'Venus',online:true,price:'$15',unit:'monthly',description:'Monitors your borrow position and repays or adds collateral before liquidation.',metrics:['24 positions guarded','7 liquidations prevented','420ms response'],accent:'#e79b88',icon:'✦',score:'4.9'},
  {id:'hf-sentinel',name:'HF Sentinel',category:'Health Factor',protocol:'Lista Lending',online:true,price:'$10',unit:'monthly',description:'A lightweight health factor watcher with configurable alert thresholds.',metrics:['11 positions guarded','4 liquidations prevented','680ms response'],accent:'#e79b88',icon:'◈',score:'4.7'},
];

const categories: {name:Exclude<Category,'All agents'>; icon:string; text:string; count:string; live:string; color:string}[] = [
  {name:'Rebalancing',icon:'⌁',text:'Keep LP positions in range.',count:'02 agents',live:'02 online',color:'#8ac6a7'},
  {name:'Grid Trading',icon:'↕',text:'Automate orders, capture volatility.',count:'02 agents',live:'02 online',color:'#e2b75c'},
  {name:'Yield Optimisation',icon:'↗',text:'Route liquidity to real yield.',count:'02 agents',live:'02 online',color:'#9eb8e8'},
  {name:'Health Factor',icon:'✦',text:'Protect positions from liquidation.',count:'02 agents',live:'02 online',color:'#e79b88'},
];

function Source({children}:{children:React.ReactNode}) { return <span className="source" title="Source: ERC-8004 Reputation Registry · Demo data">{children}<CircleHelp size={12}/></span> }

export default function Home() {
  const [active, setActive] = useState<Category>('All agents');
  const [selected, setSelected] = useState<string[]>([]);
  const [query, setQuery] = useState('');
  const [sort, setSort] = useState('Performance');
  const [view, setView] = useState<'grid'|'list'>('grid');
  const [detail, setDetail] = useState<Agent|null>(null);
  const [activate, setActivate] = useState<Agent|null>(null);
  const [step, setStep] = useState(1);
  const [activated, setActivated] = useState<Agent[]>([]);
  const [stopped, setStopped] = useState<string[]>([]);
  const [taskId, setTaskId] = useState('');
  const router = useRouter();
  const filtered = useMemo(() => { const list=agents.filter(a => (active==='All agents'||a.category===active) && (a.name+a.protocol).toLowerCase().includes(query.toLowerCase())); return [...list].sort((a,b)=>sort==='Price'?parseFloat(a.price.replace('$',''))-parseFloat(b.price.replace('$','')):sort==='Name'?a.name.localeCompare(b.name):b.score.localeCompare(a.score)); }, [active,query,sort]);
  const toggle = (id:string) => setSelected(s => s.includes(id) ? s.filter(x=>x!==id) : s.length<4 ? [...s,id] : s);
  const openActivate = (a:Agent) => { setActivate(a); setStep(1); };
  const finish = () => { if (activate) { setActivated(x=>[...x,activate]); setTaskId(`demo_task_${activate.id}_${Date.now()}`); } setActivate(null); };

  return <main>
    <header className="topbar"><div className="brand"><div className="brand-mark">✦</div><span>AGENT ATLAS</span><em>BSC MARKETPLACE</em></div><nav><button onClick={()=>setActive('All agents')}>Explore</button><button onClick={()=>document.getElementById('how')?.scrollIntoView()}>How it works</button><button onClick={()=>document.getElementById('my-agents')?.scrollIntoView()}>My agents {activated.length>0&&<b>{activated.length}</b>}</button></nav><div className="wallet"><span className="live-dot"/> BSC Mainnet <ChevronDown size={14}/><button className="connect"><Wallet size={14}/> Connect wallet</button></div><button className="menu"><Menu size={18}/></button></header>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse"/> LIVE ON BNB SMART CHAIN</div><h1>Hire agents.<br/><i>Move capital.</i></h1><p>Discover autonomous agents with a verifiable track record.<br/>Set your limits. Let them run.</p><button className="primary" onClick={()=>document.getElementById('market')?.scrollIntoView()}>Explore agents <ArrowUpRight size={16}/></button></div><div className="hero-art"><div className="constellation"><span className="node n1"/><span className="node n2"/><span className="node n3"/><span className="node n4"/><span className="line l1"/><span className="line l2"/><span className="line l3"/></div><div className="orbit-label ol1">ERC-8004 <small>VERIFIED</small></div><div className="orbit-label ol2">x402 <small>PAYMENTS</small></div><div className="orbit-label ol3">BNB CHAIN <small>LIVE</small></div><div className="core">✦<span>ATLAS<br/><small>AGENT NETWORK</small></span></div></div></section>
    <section className="stats"><div><span>ERC-8004 REGISTERED AGENTS</span><strong><Source>200,000+</Source></strong><small>Demo data · BNB Smart Chain</small></div><div><span>AVAILABLE TO HIRE</span><strong><Source>08</Source></strong><small>Demo data · across 4 categories</small></div><div><span>ONLINE NOW</span><strong className="green"><Source>06</Source></strong><small>Demo data · last checked just now</small></div><div className="stat-note">All performance data is marked when using mock mode.<br/><a href="https://eips.ethereum.org/EIPS/eip-8004" target="_blank" rel="noreferrer">Learn about verification <ArrowUpRight size={12}/></a></div></section>
    <section className="market" id="market"><div className="section-head"><div><div className="eyebrow muted">THE MARKETPLACE</div><h2>Find your edge.</h2></div><div className="market-actions"><div className="search"><Search size={15}/><input placeholder="Search agents or protocols" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="icon-btn"><SlidersHorizontal size={16}/></button></div></div>
      <div className="category-tabs"><button className={active==='All agents'?'active':''} onClick={()=>setActive('All agents')}>All agents <span>08</span></button>{categories.map(c=><button key={c.name} className={active===c.name?'active':''} onClick={()=>setActive(c.name)}><i style={{color:c.color}}>{c.icon}</i>{c.name}<span>02</span></button>)}</div>
      <div className="toolbar"><span><strong>{filtered.length}</strong> agents available</span><div><button className="sort" onClick={()=>setSort(sort==='Performance'?'Price':sort==='Price'?'Name':'Performance')}>Sort: {sort} <ChevronDown size={13}/></button><button className={view==='grid'?'view active':'view'} onClick={()=>setView('grid')}><LayoutGrid size={15}/></button><button className={view==='list'?'view active':'view'} onClick={()=>setView('list')}><List size={15}/></button></div></div>
      <div className={view==='grid'?'agent-grid':'agent-list'}>{filtered.map(a=><article className="agent-card" key={a.id} style={{'--accent':a.accent} as React.CSSProperties}><div className="card-top"><div className="agent-icon">{a.icon}</div><div className="status">{a.online?<><span className="live-dot"/> ONLINE</>:<><span className="offline-dot"/> OFFLINE</>}</div><button className={selected.includes(a.id)?'check selected':'check'} onClick={()=>toggle(a.id)} aria-label="Compare">{selected.includes(a.id)?'✓':'+'}</button></div><div className="agent-title"><h3>{a.name}</h3><span className="category-label">{a.category}</span></div><p>{a.description}</p><div className="protocol"><span>◈</span> {a.protocol}</div><div className="metrics">{a.metrics.map((m,i)=><div key={i}><Source>{m}</Source><small>{['PRIMARY METRIC','30 DAY WINDOW','RISK PROFILE'][i]}</small></div>)}</div><div className="card-bottom"><div><strong>{a.price}</strong><span>{a.unit}</span></div><div className="card-buttons"><button className="ghost" onClick={()=>setDetail(a)}>View <ArrowUpRight size={14}/></button><button className="hire" onClick={()=>openActivate(a)} disabled={!a.online}>Activate <Zap size={13}/></button></div></div></article>)}</div>
    </section>
    <section className="verification"><div><div className="eyebrow muted">WHY AGENT ATLAS</div><h2>Trust, by default.</h2><p>Every number is pulled from registries and transaction history.<br/>No self-reported claims. No black boxes.</p></div><div className="verify-grid"><div><ShieldCheck size={19}/><h3>Onchain identity</h3><p>ERC-8004 registration, owner and wallet are public.</p></div><div><span className="big-icon">⌁</span><h3>Real performance</h3><p>Metrics computed from the agent's transaction history.</p></div><div><Zap size={19}/><h3>Pay as you go</h3><p>x402 handles payment when you activate an agent.</p></div></div></section>
    <section className="how" id="how"><div className="eyebrow muted">THE FLOW</div><h2>From discovery to done.</h2><div className="flow"><div><span>01</span><h3>Compare</h3><p>Scan the metrics that matter for your strategy.</p></div><div><span>02</span><h3>Set limits</h3><p>Define exactly how much capital an agent can touch.</p></div><div><span>03</span><h3>Activate</h3><p>Pay once. The agent starts working immediately.</p></div></div></section>
    {selected.length>=2&&<div className="compare-bar"><span>{selected.length} agents selected</span><button className="primary" onClick={()=>router.push(`/compare?ids=${selected.join(',')}`)}>Compare {selected.length} <ArrowUpRight size={14}/></button></div>}
    <section className="my-agents" id="my-agents"><div className="section-head"><div><div className="eyebrow muted">YOUR COMMAND CENTER</div><h2>My agents <span className="count-pill">{activated.length}</span></h2></div><button className="ghost" onClick={()=>setActive('All agents')}>Browse marketplace <ArrowUpRight size={14}/></button></div>{activated.length===0?<div className="empty"><div>✦</div><p>No active agents yet.</p><span>Activate an agent and it will appear here.</span></div>:<div className="active-list">{activated.map((a,i)=><div className="active-row" key={i}><div className="agent-icon" style={{background:a.accent+'22',color:a.accent}}>{a.icon}</div><div><strong>{a.name}</strong><span>{a.category} · Activated just now</span></div><span className="status"><span className={stopped.includes(a.id)?'offline-dot':'live-dot'}/> {stopped.includes(a.id)?'STOPPED':'RUNNING'}</span><button className="stop" onClick={()=>setStopped(x=>x.includes(a.id)?x.filter(id=>id!==a.id):[...x,a.id])}>{stopped.includes(a.id)?'Start':'Stop'}</button></div>)}</div>}</section>
    <footer><div className="brand"><div className="brand-mark">✦</div><span>AGENT ATLAS</span></div><span>Built for BNB Chain · Main Track + TermiX Challenge</span><span>MOCK DATA <span className="live-dot"/></span></footer>

    {detail&&<div className="modal-backdrop" onClick={()=>setDetail(null)}><div className="detail-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDetail(null)}><X size={18}/></button><div className="detail-head"><div className="agent-icon" style={{background:detail.accent+'22',color:detail.accent}}>{detail.icon}</div><div><div className="eyebrow muted">{detail.category.toUpperCase()}</div><h2>{detail.name}</h2><span className="status"><span className={detail.online?'live-dot':'offline-dot'}/> {detail.online?'ONLINE':'OFFLINE'} · {detail.protocol}</span></div></div><p>{detail.description}</p><div className="detail-metrics">{detail.metrics.map((m,i)=><div key={i}><strong><Source>{m}</Source></strong><small>{['PRIMARY METRIC','30 DAY WINDOW','RISK PROFILE'][i]}</small></div>)}</div><div className="identity"><h4>ERC-8004 IDENTITY</h4><code>agent://bsc/{detail.id}</code><a href={`https://bscscan.com/address/${detail.id}`} target="_blank" rel="noreferrer">View on BscScan <ExternalLink size={12}/></a></div><div className="capabilities"><h4>WHAT IT DOES</h4><p>Automates the strategy within your limits and records actions onchain.</p><h4>WHAT IT WON'T DO</h4><p>Exceed the capital cap or act outside approved protocols.</p></div><div className="sticky-activate"><div><strong>{detail.price}</strong><span>{detail.unit}</span></div><button className="hire" onClick={()=>{setDetail(null);openActivate(detail)}} disabled={!detail.online}>Activate <Zap size={13}/></button></div></div></div>}
    {activate&&<div className="modal-backdrop"><div className="activate-modal"><div className="activate-head"><div><div className="eyebrow muted">ACTIVATE AGENT</div><h2>{activate.name}</h2></div><button className="close" onClick={()=>setActivate(null)}><X size={18}/></button></div><div className="steps">{['Connect wallet','Parameters','Pay','Done'].map((s,i)=><div className={step===i+1?'step active':step>i+1?'step done':'step'} key={s}><span>{step>i+1?'✓':i+1}</span>{s}</div>)}</div>{step===1&&<div className="step-body"><div className="wallet-box"><Wallet size={20}/><div><strong>Connect your wallet</strong><p>Your wallet is used as your identity on BNB Chain.</p></div><button className="connect" onClick={()=>setStep(2)}>Connect</button></div></div>}{step===2&&<div className="step-body"><label>Capital cap <span>Required</span><div className="input-wrap"><input placeholder="0.00"/><b>USDT</b></div></label>{activate.category==='Grid Trading'&&<><label>Trading pair<select><option>BNB / USDT</option><option>CAKE / USDT</option></select></label><label>Grid bounds<input placeholder="Lower / upper price"/></label></>}{activate.category==='Rebalancing'&&<><label>LP position id<input placeholder="Position NFT id"/></label><label>Target range width<input placeholder="e.g. 10%"/></label></>}{activate.category==='Yield Optimisation'&&<><label>Asset<select><option>USDT</option><option>USDC</option></select></label><label>Allowed protocols<input placeholder="Venus, Lista"/></label></>}{activate.category==='Health Factor'&&<><label>Lending protocol<select><option>Venus</option><option>Lista Lending</option></select></label><label>Position address<input placeholder="0x..."/></label><label>Trigger threshold<input placeholder="e.g. 1.25"/></label></>}<button className="primary full" onClick={()=>setStep(3)}>Continue to payment <ArrowUpRight size={15}/></button></div>}{step===3&&<div className="step-body"><div className="pay-summary"><span>Activation fee</span><strong>{activate.price} <small>USDT</small></strong><span className="muted-text">via Binance x402 facilitator</span></div><button className="primary full" onClick={()=>setStep(4)}>Sign & pay <Wallet size={15}/></button><p className="fine">You will approve one transaction. Your capital cap stays enforced by the agent.</p></div>}{step===4&&<div className="step-body done-body"><div className="done-mark">✓</div><h3>Agent is on duty.</h3><p>{activate.name} has been activated with your limits.</p><code>{taskId || `demo_task_${activate.id}`}</code><button className="primary full" onClick={finish}>Go to My agents <ArrowUpRight size={15}/></button></div>}</div></div>}
  </main>;
}
